### ISSUE TITLE
Will the RFLA degrade the performance on large objects ?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [Chasel-Tsui/mmdet-rfla#14]
I find that only the performance on small objects is showed in Table 7. What about the performance on medium and large objects (i.e., AP_m, AP_l) ? 
![image](https://user-images.githubusercontent.com/26771037/200162254-6ea65764-ae65-4f97-9611-e53d2bccff8d.png)

**Comment by Chasel-Tsui** [comment]
Hi, there will be a slight degradation on large objects since the k in the assigner is too small to detect large objects. As for the DIoU and CIoU based assigning, I am not sure of their performance but the Gaussian modelling can pay more attention to the center region compared to them. But if it is combined with a ranking-based assigner, intuitively, it may yield a similar result as the gaussian modelling since they can also measure the similarity of outliers.

**Comment by Icecream-blue-sky** [comment]
Have you tried setting different k for different sizes of gt? I don’t think it is necessary to use the same k for all objects, for example YOLOX sets the k value according to IoU.

**Comment by Chasel-Tsui** [comment]
Yes, you are right, setting different k for different sized gt will be much better for generic object detection. For multi-scale object detection, k should be adjusted according to its scale. But if we focus on tiny object detection, where there are many tiny objects, it is might be better to use the same k to compensate some positive samples for tiny objects. Tiny objects usually yield a low IoU with anchor or get a low IoU prediction when estimating the dynamic k, resulting in unbalanced training and lack of samples for them. I agree that the fixed k is at the cost of the degradation of large objects. I also think it is a problem worth studying to find the trade-off between sample quality and quantity/to obtain balanced training without the loss of samples for large objects.

**Comment by Icecream-blue-sky** [comment]
Thank you for your kind reply！Nice work!
